/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package roadconstruction;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author fida
 */
public class GraphicJDialog extends javax.swing.JDialog {

    private static GraphicJDialog dialog = null;

    /**
     * Creates new form GraphicJDialog
     */
    public GraphicJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel_ac.setText(jLabel_ac.getText() + ": " + Thickness.ac+" mm");
        //jLabel_dbm.setText(jLabel_dbm.getText() + ": " + Thickness.dbm+" mm"+"\n"+"CBR 90%");
         jLabel_dbm.setText(jLabel_dbm.getText() + ": " + Thickness.dbm+" mm"+" (CBR 90%)");
        jLabel_wbm.setText(jLabel_wbm.getText() + ": " + Thickness.wbm+" mm"+" (CBR 80%)");
        jLabel_gsb.setText(jLabel_gsb.getText() + ": " + Thickness.gsb+" mm"+" (CBR 30%)");
        jLabel_isg.setText(jLabel_isg.getText() + ": " + Thickness.isg+" mm"+" (CBR 8%)");
        //"<html>Hello World!<br>blahblahblah</html>", SwingConstants.CENTER
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel_ac = new javax.swing.JLabel();
        jLabel_dbm = new javax.swing.JLabel();
        jLabel_wbm = new javax.swing.JLabel();
        jLabel_gsb = new javax.swing.JLabel();
        jLabel_isg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Close");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_ac.setBackground(new java.awt.Color(1, 1, 1));
        jLabel_ac.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_ac.setForeground(new java.awt.Color(255, 254, 254));
        jLabel_ac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ac.setText("Carpeting With Seal Coat");
        jLabel_ac.setOpaque(true);

        jLabel_dbm.setBackground(new java.awt.Color(46, 46, 46));
        jLabel_dbm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_dbm.setForeground(new java.awt.Color(255, 254, 254));
        jLabel_dbm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_dbm.setText("Binder Course BM/DBM");
        jLabel_dbm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_dbm.setOpaque(true);

        jLabel_wbm.setBackground(new java.awt.Color(111, 110, 110));
        jLabel_wbm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_wbm.setForeground(new java.awt.Color(255, 254, 254));
        jLabel_wbm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_wbm.setText("Base WMM/WBM");
        jLabel_wbm.setOpaque(true);

        jLabel_gsb.setBackground(new java.awt.Color(168, 112, 77));
        jLabel_gsb.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_gsb.setForeground(new java.awt.Color(255, 254, 254));
        jLabel_gsb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_gsb.setText("Granular Subbase (GSB)");
        jLabel_gsb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel_gsb.setOpaque(true);

        jLabel_isg.setBackground(new java.awt.Color(255, 107, 0));
        jLabel_isg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_isg.setForeground(new java.awt.Color(255, 254, 254));
        jLabel_isg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_isg.setText("Caping");
        jLabel_isg.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel1.setText("BM: Bituminous Macadam");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel2.setText("DBM: Dense Bitumen Macadam");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setText("BC: Bitumen Caping");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel4.setText("WMM: Wet Mix Macadam");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText("WBM: Water Bound Macadam ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(183, 183, 183))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_isg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_gsb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_ac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_dbm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_wbm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ac, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_dbm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_wbm, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_gsb, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel_isg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dialog.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            //</editor-fold>
            UIManager.setLookAndFeel(
                    UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialog = new GraphicJDialog(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //System.exit(0);
                        dialog.setVisible(false);
                    }
                });
                dialog.setVisible(true);


            }
        });


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private static javax.swing.JLabel jLabel_ac;
    private static javax.swing.JLabel jLabel_dbm;
    private static javax.swing.JLabel jLabel_gsb;
    private static javax.swing.JLabel jLabel_isg;
    private static javax.swing.JLabel jLabel_wbm;
    // End of variables declaration//GEN-END:variables
}
